events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    resolver 127.0.0.11 valid=10s ipv6=off;

    # Только порт 80: ACME challenge + редирект на HTTPS (443 держит AdGuard)
    server {
        listen 80;
        server_name __DOMAIN__;

        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
            allow all;
            default_type "text/plain";
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
